services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: kong
      MARIADB_USER: kong
      MARIADB_PASSWORD: 1234